### ISSUE TITLE
PAC on 64-bit beta branch (NOT Chromium branch) at least 1.5x laggier than 32-bit main branch

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1016]
Title.
All outfits regardless of complexity, or _whether or not it has any web loaded content_, have a very noticeably higher framerate impact on the 64-bit branch of Gmod than on the current main branch.
For example, I tested with a very simple outfit that had no custom content that had a render time of about 2.8ms on the main branch, and switched to the 64-bit branch, where it increased to 3.8ms, and I was losing about 20-25 more FPS than normal.

I tested with a slightly heavier outfit, with these results all on gm_flatgrass:
64-bit, dev branch PAC, no mcore test params in autoexec:
4.3ms overall render time
~55 avg FPS

64-bit, dev branch PAC, applied mcore test params in autoexec:
4.9ms overall render time
~45 avg FPS
(??? Why is it worse)

32-bit, dev branch PAC, applied mcore test params in autoexec:
2.4ms overall render time
~75 avg FPS

I'm not sure if this is something fixable, but this is very concerning since 64-bit will (EVENTUALLY.) be the main branch.
My CPU is a Ryzen 5 3400g which I know isn't super great, but I'm certain this impacts everyone regardless of hardware. I'll do further testing on other machines I have.
It's distressing because even simple outfits have a nasty FPS impact that doesn't exist in 32-bit.

**Note that this was also tested in three differing versions of PAC. A custom branch based on a three year old version of it, the current workshop version, and the current developer branch version with the exact same results.**

**Comment by thegrb93** [comment]
Related https://github.com/Facepunch/garrysmod-issues/issues/4100

**Comment by Synkstar** [comment]
Have any of you ever looked at fprofiler. This is just a friends basic pac with like 9 small objs. Some people have larger ones that cripple your fps although they are not using objs. This causes lots of people to disable pac3.
![image](https://user-images.githubusercontent.com/26175394/111838044-2547c380-88cf-11eb-983e-33c17fefe267.png)
It calls a lot of functions many times. Fprofiler is good for optimizing lua on the server side and even the client side

**Comment by CapsAdmin** [comment]
Yes, I've done a lot of optimizations in the refactor branch.

I see more large scale optimizations I can do today but doing those can be tricky without breaking things.

**Comment by Synkstar** [comment]
> Yes, I've done a lot of optimizations in the refactor branch.
> 
> I see more large scale optimizations I can do today but doing those can be tricky without breaking things.

You are kinda limited by source engine and how like gmod lua works in general because lua runs on the same thread as physics and everything else. But id like to see what pac on s&box would look like if that actually gets released and is good. It would be nice if people could have like large pacs with it not lagging. It used to be better before like peoples big mechs didnt really cause much lag like years ago as far as I can remember. I find gmod as a whole is becoming less optimized too in general. I highly doubt a gmod server would be able to run on a 1ghz single core laptop with 20 people on like I did in like 2015.

**Comment by thegrb93** [comment]
gmod actually is multithreaded. The issue is jit is misbehaving in x64 gmod currently and likely causing recompiles constantly where it shouldn't.

**Comment by thegrb93** [comment]
Is there a command line to disable jit? I would like to know if disabling jit improves the performance.

**Comment by thegrb93** [comment]
Maybe add jit.off() to cl_init.lua in lua/includes

**Comment by Synkstar** [comment]
I know for sure the lua is not multi threaded. Run while true do end it freezes your game and pins a single core at 100%.  It also runs on the same thread as physics. Networking runs on a separate thread though. Trust me ive been running gmod servers for like 5 years.... That's a limitation of source engine though. But it would be cool if pac can work well without killing your frames but gmod is pretty limiting because its a 10+ year old game. Most peoples pcs back then only had 1-2 cores anyways. The best you could do to optimize stuff is limit the use of think hooks, while and for loops, and make stuff as minimalist as possible to get the same job done. Maybe for like the objects there is a way to weld it to the bone or something on the client so you don't have to constantly update it for example.( this would be possible on the server side but since pac is mainly all client side it is probably rather annoying and you would just have to minimize the use of stuff like I mentioned before. Pac3 is a large and complicated addon though. You guys put a lot of work into it so thank you. It would be cool if pac was able to like attach it or like if it could compile it as a player model but I don't think that's possible in gmod. But imagine if those pacs of like a whole character can be turned into a single not laggy player model.

**Comment by thegrb93** [comment]
You misunderstood me, I meant that the engine is multithreaded. The lua interface is not, but that's not the problem anyway. The problem is JIT.

**Comment by Synkstar** [comment]
> You misunderstood me, I meant that the engine is multithreaded. The lua interface is not, but that's not the problem anyway. The problem is gmod's botched JIT.

I disabled it and it brought my fps from 60 to 100 when someones pac is loaded(https://wiki.facepunch.com/gmod/jit.off).
I just ran that and it show it as off on my client when I do jit.status. 
What does it do when jit is turned off anyways. Does it use the one on your system instead or something

**Comment by thegrb93** [comment]
jit recompiles the lua to be faster but it's aparently broken in x64 gmod.

**Comment by Synkstar** [comment]
Im pretty sure willox mainly worked on the x64 version but they left the dev team now.(They seemed to do lots of lower level work) Ever since they left things have slowly started to go down hill in my opinion. Idk when or if the x64 version will ever come out of beta.

**Comment by thegrb93** [comment]
Going to close since it's a gmod issue and is already tracked there
