### ISSUE TITLE
Both 'aim part' and 'aim part name' exist.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1037]
`aim part` works only when targeting models
`aim part name` works only when targeting `LOCALEYES`, `LOCALEYES_YAW`, `LOCALEYES_PITCH`, `PLAYEREYES`

**Comment by CapsAdmin** [comment]
This was an intentional change to more clearly separate the two. They are really 2 separate features hacked into one. Now the "* part" functions strictly store a part's id rather than a parts name. 

The reason they are even uppercase was to avoid collision with part names, but now they can be whatever.
