### ISSUE TITLE
[Dev] SHA256 is too slow and causes server freezes on MDL downloads

### ISSUE THREAD

**Issue by Cynosphere** [CapsAdmin/pac3#1065]
Proposals: MurMurHash or SHA1 (since we aren't dealing with sensitive info that needs cryptography aspect)

**Comment by Mstrodl** [comment]
To address (malicious) collision concerns, perhaps part IDs and cache entries should be suffixed with SteamIDs. If a lua implementation of murmurhash is needed, I'm more than happy to write one :)

[Murmurhash](https://en.wikipedia.org/wiki/MurmurHash) is a good fit for this type of thing because it's not a cryptographically strong hash (it's very fast to compute), but it provides a lot of data (32 bits with good distribution).

**Comment by thegrb93** [comment]
Maybe could just hash the model's header. Dunno tho.

**Comment by CapsAdmin** [comment]
I think this is just an oversight.

I've changed all the places where I use `util.CRC` with `pac.Hash` to make changing the hashing function easier when needed.

Now that the internal hash function has changed to sha256 the mdlzip code also would also change.

I think it's best to just keep using util.CRC for mdlzip, or maybe minimize the amount of content being hashed somehow.

**Comment by CapsAdmin** [comment]
I've changed it back to util.CRC for now.

**Comment by DBotThePony** [comment]
MD5/SHA1 and SHA256 differ at computation time only slightly or MD5 turns out to be even slower when implemented on Lua

**Comment by thegrb93** [comment]
I think this was fixed by capsadmin?

**Comment by storm37000** [comment]
why do you just use the built in https://wiki.facepunch.com/gmod/util.SHA256 as its likely vastly faster, possible using c++ cpu hardware acceleration?

**Comment by CapsAdmin** [comment]
because it wasn't available at the time, but thanks for the hint!

**Comment by thegrb93** [comment]
Definitely a recent gmod addition
