### ISSUE TITLE
Stealing sounds/models/textures vulnerability

### ISSUE THREAD

**Issue by Kyosti77** [CapsAdmin/pac3#1074]
When an error occurs (for example code 404) it displays the link to download the sound/model/texture in the console which could result in people stealing other people's models/sounds/textures.

![example](https://user-images.githubusercontent.com/34723736/123112594-1cbad800-d43e-11eb-8873-0bb972a43656.png)

**Comment by DBotThePony** [comment]
but those links are useless anyway, right?

**Comment by thegrb93** [comment]
I think you could induce the http fails manually. Anyone smart enough to do that would have probably just stolen the whole outfit at that point though.

**Comment by DBotThePony** [comment]
> I think you could induce the http fails

plain http can be sniffed using wireshark or anything else. https can be broken easily by using ssl broker/bumping (e.g. squid) with self signed certificate, added to system root certs

The best way to keep your information in secret is not to share it with anyone. At least, share with those who you trust, that's why PAC3 got wear filter clientside.

**Comment by thegrb93** [comment]
Yes, use the filter if you must. There's not much that can be done in lua to prevent hackers
