### ISSUE TITLE
Add jiggle option on "new" bone part like on the legacy version

### ISSUE THREAD

**Issue by Jacbo1** [CapsAdmin/pac3#1139]
The legacy bone part has a jiggle option but the current/"new" one does not.

**Comment by thegrb93** [comment]
Looks like it does:
https://github.com/CapsAdmin/pac3/blob/a0687f158a0d6001bca1b881d594a9e0b56cb66e/lua/pac3/core/client/parts/legacy/bone.lua#L22

https://github.com/CapsAdmin/pac3/blob/a0687f158a0d6001bca1b881d594a9e0b56cb66e/lua/pac3/core/client/parts/legacy/bone2.lua#L21

**Comment by CapsAdmin** [comment]
That's the legacy bone, but the new bone does not support it due to how it renders.

It was never a good feature anyway as it often spazzed out and lacked any control. Although with more work you achieve the same effect and get more control if you use the jiggle part. Otherwise no one is stopping you from using the old bone parts if you just wanna do something quick.

**Comment by CapsAdmin** [comment]
here's an example
[jigglehead.txt](https://github.com/CapsAdmin/pac3/files/8127712/jigglehead.txt)
