### ISSUE TITLE
Small problem, annoying to me though.

### ISSUE THREAD

**Issue by lunarski** [CapsAdmin/pac3#117]
In PAC3 models I've placed floated in the air, and don't stay on my character.

**Comment by Ameno-Sagiri** [comment]
Depend on the model, but that means the model wasn't ever centered in the modelling program used to make the model in the first place. 

In particular, are you using some OBJs or Team Fortress 2 character models? TF2 models are always off centered from origin point because they were meant to be bonemerged to TF2 players, and they never needed to be in loose form. 

If you want to fix OBJs, open the OBJ in lightwave, press F2 to center its origin point, then re-save the OBJ. 

If you need to do it to an mdl in the Source, open the mdl in crafty, export it as an OBJ, open the OBJ in lightwave, and do the same thing as above. But then you need to get the textures as png's or jpg's to apply it.

**Comment by CapsAdmin** [comment]
no replies in over a month, feel free to reopen
