### ISSUE TITLE
new pac 3 update (i think new update?) broke all my avatars

### ISSUE THREAD

**Issue by local-gmod-player** [CapsAdmin/pac3#1173]
![20211112201828_1](https://user-images.githubusercontent.com/101485572/158040638-582e8e85-0684-4c1e-8628-ee6c7e212b29.jpg)
this is one of my avatars
This is my favorite one
(it looks better)
but now it looks like this
![20220312190845_1](https://user-images.githubusercontent.com/101485572/158040647-b01e46f0-9093-4025-9053-6c5fd5b1a926.jpg)

this is a problem i only had now

this is the first time posting in

**Comment by thegrb93** [comment]
Can you give the file for us to test with? It's in garrysmod/data/pac3

**Comment by local-gmod-player** [comment]
[gas station weed.txt](https://github.com/CapsAdmin/pac3/files/8249032/gas.station.weed.txt)
[gastation.txt](https://github.com/CapsAdmin/pac3/files/8249033/gastation.txt)
theres 2 files incase one of them broke or to add new things

both of them broke

**Comment by pingu7867** [comment]
I think it's up to the main box being below the entity, mostly. You shouldn't put models inside entity parts. Only put models inside models, groups or events.

I fixed it up a bit, hopefully it'll work. I separated some of the stuff off of the main group, into the main box, for organization and easy moving for the face.

[gastation_weed_maybe_fix.txt](https://github.com/CapsAdmin/pac3/files/8258659/gastation_weed_maybe_fix.txt)


Now some part of this problem is yours to attribute, using a weird pac structure, but absolutely there is some responsibility that is the devs' when it comes to what stuff gets changed. There should be better notices for when part positioning and orientation gets changed. Or not play with it too much at all. It's always this that breaks pac in updates. Translucent stuff, alpha, parent parts' type... these things get involved in how children parts get positioned. Why?? I shouldn't have to understand it, but I can see what stuff usually coincides with these issues. Anyway I'll try to narrow it down and make an issue that I hope will be more direct...

**Comment by local-gmod-player** [comment]
Thank you for telling me this

I will use this advice in the future for making pac3 avatars

**Comment by thegrb93** [comment]
> You shouldn't put models inside entity parts.

I'm not sure why this would break it. Maybe we can fix it. Will look soon.

**Comment by pingu7867** [comment]
I mean, before (might be an older thing than what I think), if you played with the entity position, it used to break more (like, the player would snap out of its standing position, rotate 90 degrees down left or something), but I guess you guys made some cool innovations to fix it.

My point is that conceptually it's not really coherent to affix a model on an entity MODIFIER. The root group should be where we put stuff directly on the player. That's what I think at least.

**Comment by thegrb93** [comment]
I believe my latest update fixed this. We just need to push the fixes to workshop.

**Comment by thegrb93** [comment]
I tested your outfits and they are indeed fixed
