### ISSUE TITLE
Particles not angling correctly when 3d option is enabled

### ISSUE THREAD

**Issue by unknao** [CapsAdmin/pac3#1222]
Particles created by the particle part with 3d option enabled while not set to "follow" seem to completely ignore the pitch entirely.

[3dparticle.webm](https://user-images.githubusercontent.com/24782457/186258600-cc6cf817-e625-45cd-9698-56241a139219.webm)

**Comment by Yagira** [comment]
Seems like this is caused by the roll settings which apparently shouldn't be used with 3D particles, but I guess some people might like the effect it creates so instead of disabling it completely it's just going to be ignored when set to 0. You can test it here https://github.com/CapsAdmin/pac3/archive/develop.zip and see if it fixes your issue.
