### ISSUE TITLE
Previously fine outfit spews non-sensical warnings consistently

### ISSUE THREAD

**Issue by Earu** [CapsAdmin/pac3#1359]
I get keep getting these warnings:
`Invalid model scale 0.000000 for class C_BaseFlex[-1] (x55)`

I use the new model parts (not the legacy ones). The problem continues to happen until I remove every model part in the outfit.

**Comment by TW1STaL1CKY** [comment]
Can confirm - this is printed for each model part rendered on screen. It doesn't matter what the model part's size/scale is set to.

I should add that this is happening on the current x86-64 branch of gmod, just in case this isn't an issue on the main branch. There have been quite a few changes to the x86-64 branch lately so that is likely to have caused this to start happening.

**Comment by DruCart3456** [comment]
Same here, though it doesn't help for all specific parts; it only happens to me if the part I have loaded is _specifically,_ an OBJ. Why this is, I have no idea, but it only happens with an OBJ loaded. The entire rest of my pac is valid. Very odd.

**Comment by DruCart3456** [comment]
Experimented with this for a bit, messing around. I can't confirm it, but I assumed at first it had to do with OBJs, as my pac only created this error when a set of generic spheres I grabbed from Blender I was using for eyes were loaded. Turning it into an MDL properly, it still created this error, but its the only model on my pac that does it.

_However,_ after triangulating all faces in Blender rather than letting Crowbar do it automatically... this has seemingly fixed it. Will edit / delete this comment if it comes back up and the reason is not consistent, but it seems to be any models loaded that aren't triangulated before being compiled.

**Comment by Asiliria** [comment]
I've received constant complaints about this issue - I agree with DruCart, but at the same time, it still seems to occur even when all my OBJ parts are not loaded/fully removed. I'm leaning more towards the x86-64 branch changes that were mentioned introducing this bug, as the Linux build has been very active these past few months.

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/blob/48743b7bd75c274cdc25c963387b98fa65ae0015/lua/pac3/core/client/parts/legacy/model.lua#L412

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/blob/48743b7bd75c274cdc25c963387b98fa65ae0015/lua/pac3/core/client/owner_name.lua#L49

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/blob/48743b7bd75c274cdc25c963387b98fa65ae0015/lua/pac3/core/client/parts/model.lua#L581

https://github.com/CapsAdmin/pac3/blob/48743b7bd75c274cdc25c963387b98fa65ae0015/lua/pac3/core/client/parts/model.lua#L441

**Comment by thegrb93** [comment]
I'd complain to the gmod dev. Seems dumb for 0 to be an invalid scale.

**Comment by Techbot121** [comment]
I think this error was added to prevent dividing by zero? but also you cannot go negative anymore
well anyway I did push a fix for develop since it really *is* annoying.

see fb65d1b
