### ISSUE TITLE
How to make my saves independent playermodels

### ISSUE THREAD

**Issue by Sir-Ankylosaurus** [CapsAdmin/pac3#185]
I was using pac3 to make some dinosaur player models out of one playermodel. However, when I go to select my playermodel, only the original playermodel comes up, I need to actually use pac3 to switch my playermodel. Is there a way I can turn each outfit into its own playermodel that I can select on the playermodel menu? I plan on making NPC's out of them and if what I asked is not possible, is there a way I can turn each of them into a ragdoll that I can save as a dupe, that will also work for me. 
Please respond, Thanks!

**Comment by LUModder** [comment]
See https://github.com/CapsAdmin/pac3/wiki/PAC-in-gamemodes

Also entity part will be useful.

**Comment by Sir-Ankylosaurus** [comment]
Which of those should I use? I'm sorry, I've never done LUA.

**Comment by Sir-Ankylosaurus** [comment]
It's very unclear, there's no clarification, can you please add me on steam? Every other person I asked for help has straight out ignored me, and after posting here (I actually deleted my last post because nobody responded after 6 days although all the others weren't ignored) twice, and on the profiles and comments sections of admins and pac 3 guides, I am not really in the mood for waiting longer, I've been asking this question for 2 weeks now. I apologize if it seems like I'm going at you, I do thank you for being the first and ONLY person to respond to me.

**Comment by CapsAdmin** [comment]
Add the entity part and select your player model in the model field. You can also use player model names in there too, like "mossman" and "breen". This model is then applied whenever you wear the outfit.

If the server is not sandbox this is a feature that needs to be turned on with "pac_modifier_model 1". (it's off by default outside of sandbox because this can be used for cheating)
