### ISSUE TITLE
black triangles when using phong in material

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#188]
Only happens after a changelevel and it seems to mostly affect older gpus.

**Comment by thegrb93** [comment]
Happens with lightwarps too I think.

**Comment by CapsAdmin** [comment]
also only an issue with obj

**Comment by CapsAdmin** [comment]
I'd really like to fix this as it scares people away from using some material features to make things look prettier. Maybe it has to do with bad normals?

**Comment by Ameno-Sagiri** [comment]
Yes I know this is old.
I was just recently having this very same problem. Bothering me a lot because I was planning on using this extensively on some PACs.

I have noticed that for certain textures and models, this problem doesn't happen. For example, I made a Promethean Knight from Halo 4 and it uses a lot of things from material parts to make certain parts of the textures glow. No problems there, but recently I can't make a Fallout 4 Mr. Handy model have reflective and shiny looking metal because PAC material parts refuse to work with the normals. I have tried 1024 and 512x512 texture sizes, still get the random black triangle problem. Also sometimes get full white or full black.
