### ISSUE TITLE
Camera Jittering of Player Entity size greater or less than 1 (Solved)

### ISSUE THREAD

**Issue by LightningFlash** [CapsAdmin/pac3#201]
as said in the title, not entirely sure what causes the issue but yeah.

Essentially the camera tries to reset to where it would be of player size was 1 but keeps flickering back and fourth, complete with bouncing

**Comment by LUModder** [comment]
Server desync bug. Clear twice and rewear

**Comment by LightningFlash** [comment]
still happening

**Comment by LUModder** [comment]
Do you happen to have two entity parts in the PAC?

**Comment by LightningFlash** [comment]
checked earlier , i do not.

**Comment by LUModder** [comment]
Have you tried NOT being in singleplayer?

**Comment by LightningFlash** [comment]
im not in singleplayer

**Comment by LUModder** [comment]
I'm outta luck on how to fix it then. Maybe someone else can help.

**Comment by LightningFlash** [comment]
alright, thanks anyway

**Comment by Python1320** [comment]
Try using the metastruct's "active" branch https://github.com/metastruct/pac3 to see if the flickering stops. It has rewritten player scaling. Either the scaling will work or reset to normal but it should have no constant flickering anymore.

**Comment by LightningFlash** [comment]
i managed to fix it, just using size 1.0 now

**Comment by Hazbelll** [comment]
I can give some insight here. @LightningFlash is a regular user on my Server and the issue he's referring to here is actually more so to do with my own script that alters ViewOffset depending on your Player Model. I apologise that he came directly here rather than leaving the issue with me, as it's my responsibility in this case.

As we're here now, I might aswell enquire about it. Essentially, this is how my script works:
* Check to see if LocalPlayer's model is in a certain file directory every second.
* Check to see if LocalPlayer's current ViewOffset is correct for that Player Model. If it is, the script ends here and waits until the next second to re-check.
* If their ViewOffset isn't correct for their Player Model, set it to what it should be and then send it to the server so the client and server remain in sync.

The script is necessarily as if a player so much as open's the PAC editor or loads a PAC directly, their viewheight gets reset to stock, even if their player model hasn't changed. It works without issue too, however if they alter they Player Entity size in PAC to any value but 1, their viewheight will shake up and down.

My script doesn't scale the ViewOffset's vector values based off their size. I'd like it to and should look into getting it to do so. However, the camera shake is only present if the player's entity is scaled through PAC, not via DarkRP or typical means. I was actually working on fixing it right now and added a hotfix to check to see if the Player's entity scale was a value of 1, if not, end the script prematurely until the next second, but it didn't work. Reason being:
```lua
] lua_run_cl print(LocalPlayer():GetModelScale())
1
[PAC3] Your part my outfit has been applied.
] lua_run_cl print(LocalPlayer():GetModelScale())
1
```
GetModelScale() still returns a value of 1 when using PAC to change the Player Entity's size. I've not yet looked into how PAC does it. I know this isn't a help forum, but would you be able to point me in the right direction?

**Comment by LUModder** [comment]
Use Meta's branch then. Should fix it.

**Comment by Hazbelll** [comment]
I'll give it a go and see, thanks.

Any E.T.A on the Workshop version getting updated to the latest? It's been a while and I do prefer using Workshop whenever I can.

**Comment by Hazbelll** [comment]
Sorry for the late response. I've tested Meta's active branch and that fixed the "earthquake" issue. Thanks!

I just added https://github.com/Metastruct/pac3/blob/3194456daec96fc90bdba562ee36c2fd433caf16/lua/pac3/core/client/hooks.lua and https://github.com/Metastruct/pac3/blob/3194456daec96fc90bdba562ee36c2fd433caf16/lua/pac3/core/shared/modifiers/size.lua into their respective directories in an addons folder on the Server and it's working perfectly.
