### ISSUE TITLE
Forced draw distance

### ISSUE THREAD

**Issue by Fred-FredBurger** [CapsAdmin/pac3#284]
Somehow, pac's been forcing my draw distance to 9000 in every single server I've been on.. pretty much means that small maps in pac servers = really bad fps. No matter what number I've set the draw distance  to in console or the spawn menu it just stays the same, it really makes being in pac servers pretty difficult when I'm forced to pac_restart when the lag's too ridiculous to handle.

These problems started happening about the time the newest workshop version update went up which was on February 2nd. I uninstalled the workshop version switched to the github one in hopes that this more updated version would fix it... sadly no luck. I also cleared the downloads and cache folders in my gmod folder... once again no luck.

**Comment by LUModder** [comment]
Cannot personally confirm but @ToastyEngineer has had this happening for a while now.

**Comment by ToastyEngineer** [comment]
Yep same here. 
I wish I knew how to fix it. Maybe look at the code but I cant even find the draw distance code.
send help

**Comment by Fred-FredBurger** [comment]
I know where it is actually. It's literally named drawing.lua

**Comment by ToastyEngineer** [comment]
Alright found it. I'll mess around with it a bit. Maybe I can find a solution.

**Comment by ToastyEngineer** [comment]
**FOUND A SOLUTION**
The convar "pac_sv_draw_distance" is to blame.
Your clientside value will most likely return something that isnt 0. You can check by just typing in "pac_sv_draw_distance" in console.
Now to fix it you need to ask someone who can change that value SERVERSIDE (console/cmd)

1. (optional if it isnt 0 already) Lua way: game.ConsoleCommand("pac_sv_draw_distance 10\n") or
    CMD way: pac_sv_draw_distance 10
2. Lua way: game.ConsoleCommand("pac_sv_draw_distance 0\n") or
    CMD way: pac_sv_draw_distance 0
3. Profit.

Thanks to [Nerd Koopa](http://steamcommunity.com/profiles/76561197995187362/) for testing.

**Comment by 00875** [comment]
This is gmod convar replication bug and it was fixed by Willox in gmod dev
branch

*FOUND A SOLUTION*
The convar "pac_sv_draw_distance" is to blame.
Your clientside value will most likely return something that isnt 0. You
can check by just typing in "pac_sv_draw_distance" in console.
Now to fix it you need to ask someone who can change that value SERVERSIDE
(console/cmd)

   1. (optional if it isnt 0 already) Lua way:
   game.ConsoleCommand("pac_sv_draw_distance 10\n") or CMD way:
   pac_sv_draw_distance 10
   2. Lua way: game.ConsoleCommand("pac_sv_draw_distance 0\n") or CMD way:
   pac_sv_draw_distance 0
   3. Profit.

Thanks to Nerd Koopa <http://steamcommunity.com/profiles/76561197995187362/>
for testing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/CapsAdmin/pac3/issues/284#issuecomment-217635259>
