### ISSUE TITLE
PAC not using UV map as other programs do.

### ISSUE THREAD

**Issue by pugking9** [CapsAdmin/pac3#285]
PAC seems to not like my UV mapping, despite what looks correct to every program used to view it so far.
![How it should look](http://i.imgur.com/ub1jXm2.png)
![How it does look](http://i.imgur.com/yKtQGe4.png)

**Comment by LUModder** [comment]
Not an issue on PACs side

Use material part and move the position I guess

**Comment by pugking9** [comment]
Made an attempt to do so already to no avail.
Suppose I'll start from scratch.

**Comment by thegrb93** [comment]
@LUModder Yes it is an issue with pac. It's because pac won't load texture coordinates <0 or >1 correctly.

**Comment by LUModder** [comment]
@thegrb93 I wasn't trying to start shit because I know you or someone else was going to call me out on it. Just fucking drop it

**Comment by thegrb93** [comment]
Stop making rash assumptions and you won't get called out.

**Comment by LUModder** [comment]
@thegrb93 Stop being self-centered. I've already had enough drama for today I don't want more to start.

**Comment by thegrb93** [comment]
Does anyone know why the uvs are being wrapped? https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/libraries/urlobj/urlobj.lua#L240

@pugking9 
Try changing those lines to this and see if it works.
```
texCoordsU[texCoordIndex] = u
texCoordsV[texCoordIndex] = v
```

**Comment by CapsAdmin** [comment]
I think there was a reason behind it but it probably wasn't a good reason. What about the different wrap modes like repeat, mirrored repeat and clamp to edges? uv%1 would be repeat

**Comment by thegrb93** [comment]
No, uv%1 causes this
![clamp](http://i.imgur.com/vB02P7N.png)

**Comment by CapsAdmin** [comment]
I'm not sure what you're saying. if x is 1.1 it would be 0.1. This is repeating like your first example isn't it?
 
Also I think I remember now, It was because the wrapping was clamped to edges with black borders so anything beyond 1 and below 0 would be black. Is there a way to change this behavior in gmod? (It's been a while)

**Comment by thegrb93** [comment]
I bet it's because because the texture is coming from the html vgui which probably has the clamp uv flag set. I don't think there's a way to modify ITexture's flags, but I think you could take an ITexture with repeat flags and use render.CopyTexture to copy the html texture to it. Idk if the flags get copied, but I doubt it.

**Comment by thegrb93** [comment]
Oh, and my example illustrates how the textels are interpolated with 1.1 vs 0.1. If you give it 0.1 then it will interpolate across the image to 0.1, but if you give it 1.1 then it will interpolate over the edge of the image across to the other side.

**Comment by CapsAdmin** [comment]
Are you using linux or osx?

**Comment by SladeXanthas** [comment]
I am having this same issue.  Model looks perfect in everything but PAC.  The texture repeats itself at the base awkwardly, and I don't know how to fix it.

![image](https://cloud.githubusercontent.com/assets/5251535/17834310/1e203f62-6708-11e6-933b-80ee58f3b9d2.png)

**Comment by thegrb93** [comment]
@CapsAdmin Missed that question, I'm on windows.
