### ISSUE TITLE
Hand Stretch Glitch

### ISSUE THREAD

**Issue by Yeomango** [CapsAdmin/pac3#357]
I've been having this problem, once a bone merge another ragdoll I get this
http://steamcommunity.com/sharedfiles/filedetails/?id=836600316
But now on my server, just certain models (which we NEED) are doing this.

**Comment by TW1STaL1CKY** [comment]
This happens because the model you are trying to bone merge has extra finger bones than your playermodel. For example, if your playermodel has 3 finger bones whilst the bone merging model has 5, the extra 2 fingers stretch and go to pos 0,0,0 as they have nothing to properly bone merge to.

If your playermodel is a citizen, which has 3 finger bones, then change your playermodel to one that has 5 finger bones such as Breen - this can be done using the entity part. Once you've done that, try bone merging again and there should be no stretchy hands/fingers.

**Comment by Yeomango** [comment]
That worked, thank you so much!
