### ISSUE TITLE
Effects Broken

### ISSUE THREAD

**Issue by man03** [CapsAdmin/pac3#389]
I'm having trouble with effects. Whenever I set up an effect without wearing it, it seems to work half the time, and only once, but if I wear it, it stops working, as in the effects don't render. They work just fine when I join a server with them on autowear, but as soon as I change anything and wear it, they stop working.

**Comment by DatAmazingCheese** [comment]
When using effects, instead of creating an effect, create a model. Then put the effect on that.

**Comment by AeoMayo** [comment]
The above doesn't work. This seems to be a semi-widespread issue as I (along with all of my friends) have been having this problem as well for a long time, after a Gmod update months ago. Don't remember which one :x Tried many fixes, and I had been doing the put-on-model thing previously due to other issues like more than one effect not being able to play at the same time on a singular model. Old issue, but this issue is entirely different.
