### ISSUE TITLE
PAC no longer renders in areas where skybox doesn't render.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#478]
Ever since commit "f78857f New entity draw ignore - roboderpy", PAC no longer works at all in render cordons that don't contain the map origin. Only parts that contain translucency are left rendered, and being underwater shows the missing parts. Only the void renders all stuff consistently. This doesn't happen on all maps, but still on a good chunk of them. Good testing examples are gm_carcon_ws and gm_construct_m289. The last commit where this doesn't happen, is "b0633d5 Update projectile.lua - Python1320".
EDIT: Thanks to FreezeBug for figuring out the real cause. Title changed, see his comment.

**Comment by roboderpy** [comment]
Try Misc Fixes commit. New entity draw ignore commit is broken and i know it.

**Comment by nerdkoopa** [comment]
I can't use that if it still contains the bone break glitch that you introduced.

**Comment by nerdkoopa** [comment]
Seriously, the Misc Fixes commit right now is worse than the current one. It doesn't contain Caps's fix for when you broke bones.

**Comment by TheFreezebug** [comment]
Not so much,   

The issue appears to be that if a map has a 3D skybox and it's not being drawn, neither does PAC.

Your outfit will also draw inside of water if you have world reflections on, because it reflects the skybox.

**Comment by TheFreezebug** [comment]
![that didn't load.](http://xayr.ga/share/2017-09/hl2_2017-09-03_13-34-29.png)

In this area, PAC does not render, on the top left of the screen listed are the arguments for PostDrawOpaqueRenderables. 

![that didn't load either](http://xayr.ga/share/2017-09/CUE_2017-09-03_13-35-44.png) 

Seen here, both arguments of PostDrawOpaqueRenderables are false.  PAC Draws here.

**Comment by CapsAdmin** [comment]
That extra check is probably why. Looking at git blame it was added 7 days ago by dbot. 

Ideally i'd like to get away from this hook and use something else that isn't called multiple times a frame. I think there was another hook that I can use.

**Comment by TheFreezebug** [comment]
Yeah, it was added in the Optimization commit [e9ced8f5ff89 . . .](https://github.com/CapsAdmin/pac3/commit/e9ced8f5ff89ca11a214ce6b247c2faf069cb3dd#diff-37bd11f01a0d48a6db22afe0abd2e936R377) 

You could add a check to make sure that PAC only executes on the last call of PostDrawOpaqueRenderables if there's no suitable hook to replace it. 

Seeing the [Render Order](https://wiki.garrysmod.com/page/Render_Order) there's not much option for hooks that are 3D, called once a frame, and are called after PostDrawOpaqueRenderables (Because we don't want to be drawn over).

**Comment by CapsAdmin** [comment]
That's what it's doing atm but it has side effects like flickering when the amount of draw calls changes.
