### ISSUE TITLE
Projectiles not functioning when spawned at a distance

### ISSUE THREAD

**Issue by Sounalius** [CapsAdmin/pac3#536]
As of the recent July 26th stable build released to Steam, I've noticed that the hitpos bone is no longer visible. Additionally, adding physical projectiles, and placing them at a distance from the player (roughly 600 in any direction) causes them to spawn at the invalidbone position regardless. Unchecking physical will cause them to function properly.

**Comment by AeoMayo** [comment]
The projectile spawn distance limit is intentional behavior to prevent greifing. Personally I edited the lua of the projectile part on my server to increase the distance to 99999999 since its a private server anyway where randoms wouldn't matter. As for the hitpos bone disappearing, not sure. Heard other people have this happen but typing in the bone name should still work.

**Comment by Sounalius** [comment]
Any chance you edited the life time of projectiles, as well? They seem to only last ten seconds, regardless of the value entered, and I cannot seem to find the reason...

**Comment by AeoMayo** [comment]
Sorry for the late response, I don't check my email very often..

I have not, but the lifetime on projectiles is clamped for the same reason, to prevent people spamming them and crashing the server because they don't de-spawn fast enough.

It's line 401 in projectile.lua in the shared lua folder.
`SafeRemoveEntityDelayed(ent,math.Clamp(part.LifeTime, 0, 10))`

Line 381 is the projectile spawn distance limit.
`if pos:Distance(ply:EyePos()) > 999999999999 * ply:GetModelScale() then`

Note that the version of PAC I'm using on my server is somewhat out of date, so there's a possibility that it could be changed. Using Notepad++'s find function may make it easier to find these snippets if they've been changed or moved.
