### ISSUE TITLE
Bone scale bug on death ragdollize parent

### ISSUE THREAD

**Issue by Donatea** [CapsAdmin/pac3#555]
Is it a known bug that bone scaling does not properly apply to death ragdolls? Bones with scaling modifiers would spazz out uncontrollably upon death without properly mapping to their correct sizes.

**Comment by TW1STaL1CKY** [comment]
I was going to post about this again since it is still happening since the last time I tried to fix this.

Here is an example PAC that has the issue:
[https://dl.dropboxusercontent.com/s/eoumut9i2hkyzzr/example_death_ragdollize_bone_parts_bug.txt](https://dl.dropboxusercontent.com/s/eoumut9i2hkyzzr/example_death_ragdollize_bone_parts_bug.txt)
Die with it worn and you should see that the head grows at the rate you have set in the Scale/Size setting, like it is additive.

**Comment by roboderpy** [comment]
Source engine limitations. Source doesn't allow to scale bones on ragdolls. It is also known issue with ppm2 death ragdolls.
