### ISSUE TITLE
UV wrapping is set to 'clamp'

### ISSUE THREAD

**Issue by thegrb93** [CapsAdmin/pac3#593]
Need a way to change the ITexture uv wrapping flag for custom textures. They are taken from DHTML panels which have ITexture uv wrapping set to 'clamp'.

Work-around: Create a new rendertarget and render the DHTML texture to it.

**Comment by roboderpy** [comment]
Easier: create an html panel with js code which clamps and adjucts texture to valid state

**Comment by thegrb93** [comment]
https://developer.valvesoftware.com/wiki/Valve_Texture_Format#Image_flags

Clamp S | 0x0004
Clamp T | 0x0008

**Comment by roboderpy** [comment]
Ah you are about inability to create tiled textures

**Comment by thegrb93** [comment]
Yeah

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/735

**Comment by roboderpy** [comment]
it can be unstable like as SetShader method. Better to create new texture

**Comment by CapsAdmin** [comment]
It's better to use the system that material2 and whatnot uses for this I think.

**Comment by roboderpy** [comment]
I think @CapsAdmin know more how to implement it, because i badly deal with stuff2 things. It is simple straight simple - new function to extract url texture  by making url texture be forced to size as target size, doing `render.CopyTexture` html -> render target and returning material with rt and no clamp.

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/c73bcb2e6e3adc3821fbebd96b567580d26227dc
