### ISSUE TITLE
Model2 manual bonemerge only works after the model has fully downloaded

### ISSUE THREAD

**Issue by Jarmmo** [CapsAdmin/pac3#598]
Forcing you to reload the outfit

**Comment by Delta983** [comment]
Also: I noticed If you have a model2 with some bones that you resized- you'll have to wear the pac 2 times in order for the bones to be the size you intend them to be, If you only wear the pac once the model's bones will all be size 1 instead of say.. 0.7 that you want It to be, forcing you to reload it for it to actually show for others.

**Comment by CapsAdmin** [comment]
I'm pretty sure I fixed this. Reopen if not.
