### ISSUE TITLE
Massive exploit that lags the entire server

### ISSUE THREAD

**Issue by CubXD** [CapsAdmin/pac3#646]
https://hastebin.com/zurayipogu.cs

Someone got on and started exploiting and lagging the server, the only thing that errored was pac so I assume it's related to pac.

**Comment by thegrb93** [comment]
Sure it's not ULX?

**Comment by SladeXanthas** [comment]
The 'exploit' in PAC in particular is only the lag issue.  Anything else that was happening to the server would have been executed elsewhere.  Basically, this happens because of either sending invalid net messages or too many at once (ie: telling PAC to send outfits a ridiculous amount of times in a short timeframe.)  This should at least help curb the issue:

https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/essential/autorun/server/net_receive_protection.lua

Drop this into lua/autoun/server/.

**Comment by CubXD** [comment]
I'm just gonna assume the lua file linked will solve my issue. Not as if im gonna get the dude back on the server to try again. Thanks @SladeXanthas
