### ISSUE TITLE
Attached models do not have properly scaled render bounds

### ISSUE THREAD

**Issue by besenyei** [CapsAdmin/pac3#654]
pac3 doesn't scale render bounds with model size.
r_drawrenderboxes 1 (requires sv_cheats 1)

![20180530210022_1](https://user-images.githubusercontent.com/39219459/40744525-b635d2ec-644c-11e8-8442-afa1524f7b13.jpg)

**Comment by roboderpy** [comment]
This is something source engine related, not sure if we can fix it

**Comment by besenyei** [comment]
I know render bounds can be controlled with https://wiki.garrysmod.com/page/Entity/SetRenderBounds
I wonder if render bounds could be scaled with model size, or removed.

**Comment by besenyei** [comment]
If it's not possible at all, I'll make a request on gmod requests to have [SetModelScale](https://wiki.garrysmod.com/page/Entity/SetModelScale) also apply or extend it to render bounds.

**Comment by roboderpy** [comment]
I read wrong and I were thinking about clientside traces hitting pac3 outfits. 
Oh and also - pac3 manually draw models (and handle visibility check of outfits)! Changing render bounds will have no effect at all, because DrawModel call draws model despite the conditions where is it relative to current 3D scene camera position.

**Comment by besenyei** [comment]
I see, thanks for clearing my misconceptions.
