### ISSUE TITLE
Chromium loads random textures

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#670]
When using Chromium instead of Awesomium, it loads random ingame textures instead of custom images. Sometimes this happens instantly, other times only after loading the outfit again. The issue can't be undone with restarting or clearing caches.

**Comment by roboderpy** [comment]
Did you tried develop branch of pac3? 18:33, 11 июля 2018 г., nerdkoopa <notifications@github.com>:When using Chromium instead of Awesomium, it loads random ingame textures instead of custom images. Sometimes this happens instantly, other times only after loading the outfit again. The issue can't be undone with restarting or clearing caches.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by lilggamegenius** [comment]
We were on the pac server which uses develop

**Comment by willox** [comment]
It's possible that IsLoading could return true after:

1) You've already successfully loaded one page
2) You've started loading another page (`Panel.OpenURL`)
3) You call `Panel.IsLoading` before `Panel.OnBeginLoadingDocument` executes

Any idea if any of that is true? I don't think it would be hard for GMod to update the game thread's loading state during step 2.
