### ISSUE TITLE
Can't see third person's PAC

### ISSUE THREAD

**Issue by QuantumAvali** [CapsAdmin/pac3#710]
When I'm playing with one of my friends, we can both see each others PAC just fine, but when we have another friend join us we can't see their PAC even though they can see everyone's PAC including their own

**Comment by thegrb93** [comment]
Might need a copy of their outfit to reproduce the issue, there's nothing else we can do with the limited information given.

**Comment by thegrb93** [comment]
What happens if one of you two wear the third person's outfit?

**Comment by QuantumAvali** [comment]
We tried wearing the outfit they were wearing and we were all able to see it on each other with the exception still being the third person

**Comment by thegrb93** [comment]
Are they pac banned? Try pac_unban "their name or steamid"

**Comment by pingu7867** [comment]
I've went on people's servers a few times to investigate this issue before, and found that the only reason people would not see others' pacs is that there's blacklisting going on. Sure enough that is the best lead I found. Pac randomly blacklists people for other people. I see this because though I don't check anyone on any if the two blacklists in pac and settings sections of the spawnmenu, I sometimes see some people checked on in one or the other blacklists.

**Comment by thegrb93** [comment]
Make sure their pac_wear_reverse and pac_wear_friends_only are 0. Those can keep their outfit from sending to other players.

**Comment by thegrb93** [comment]
pac_wear_reverse makes the blacklist turn into a whitelist.

**Comment by thegrb93** [comment]
Also make sure they have you both unblocked. All those settings can be found in the q menu/options/pac3 I believe

**Comment by thegrb93** [comment]
Probably related to the cookie issue that was just fixed
