### ISSUE TITLE
Submaterials 'leak' onto a player's base model when applied to models

### ISSUE THREAD

**Issue by textstack** [CapsAdmin/pac3#774]
**Steps to reproduce**
1. Add a model to an empty pac
2. Put a submaterial onto that model, use any material
3. Save the pac
4. Load the pac

Clearing the pac immediately will cause the submaterial to properly clear, but deleting the model before clearing will cause the submaterial to persist. 

I have heard that players with pac3 disabled can still see the persisting submaterial, though I haven't tested this in newer versions of pac. 

The only way to fix or prevent this persisting without resetting the game is by adding a new submaterial onto the base group.

**Comment by roboderpy** [comment]
cannot reproduce 
![hl2_19-06-26-7a99e32](https://user-images.githubusercontent.com/6339511/57016433-39836880-6c44-11e9-99df-ca141118c5b4.png)
please test with develop branch

**Comment by Yagira** [comment]
Well I'm afraid you messed up the test. The "leak" happens between the material ids, default material on the sphere (id 1) will leak onto the entity material with id 1, in most cases the head, and you just covered the head with a sphere. Also it doesn't happen until you wear the outfit.

![image](https://user-images.githubusercontent.com/12747052/57017606-1ba40c80-6c20-11e9-9168-478cc4ac7d01.png)

And the simplest solution is to put an empty submaterial on your entity with the same id.

![image](https://user-images.githubusercontent.com/12747052/57017761-d59b7880-6c20-11e9-9ca7-926f1220e71b.png)

It's been like this since i remember. Yes, it's the latest develop branch.

**Comment by roboderpy** [comment]
not just owner

**Comment by roboderpy** [comment]
Fixed
