### ISSUE TITLE
Disable 'hide mesh' on experimental bone part.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#783]
Some time ago it has been disabled on the normal bone part, but it still exists on the experimental one and can be heavily abused. (I'm talking about the ragdoll crash)

![image](https://user-images.githubusercontent.com/12747052/57206304-02ef7a00-6fc5-11e9-9a1f-73f4a3c84e38.png)

**Comment by pingu7867** [comment]
Or make bone2's hide mesh stuff only work on model1 or model2 rather than the player, or disable the part before the player is ragdolled if possible. It's not a new thing that parts can only be used under certain compatible part types. I don't see how it wouldn't be possible to hardcode something like that.

**Comment by thegrb93** [comment]
I think it's patched now.
