### ISSUE TITLE
Submaterials are broken (sorta)

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#812]
Whenever I load up an outfit, and I especially noticed this with a certain one (I made an outfit that goes to SGM's Toyota Sprinter Trueno which gives it foglights, the 13-954 plate, and black Watanabe RS rims), where the Submaterials apply to the outfit, but for some reason it also puts the submaterial on myself as well. Don't know why. I also noticed this a while back when I made a PAC outfit with events where when I sit down my character has a laptop and it plays typing sounds, and I gave the screen a submaterial to go with it, but when I load up the outfit the submaterial works for the screen but also applied it to my head (I think this is because my submaterial ID was like 1 or something, and that's the ID of the laptop screen but also the ID of my head texture for my own playermodel). So yeah, it works, but it applies it to myself as well as the outfit owner. It doesn't happen when I'm actually making the outfit, just when I load it in and wear it. I can't fix it by any means it seems. I've tried changing playermodels, the Submaterial's ID, the outfit owner name, and so forth.

**Comment by thegrb93** [comment]
It would help motivate fixing the issue if you upload an example of a broken outfit.

**Comment by Yagira** [comment]
If you are talking about old submaterials then it was fixed (check #774). However there is still a problem with new materials which i reported in #778, the issue was closed but the problem remains. I narrowed it down to the material override setting, by default its set to "all" which is meant to replace all materials on the parent model but it also replaces materials on other entities. 

It even affects other players. Here you can see a material "leaking" from Iska to me because we both use Alyx.

![hl2_JkamLGNWu5](https://user-images.githubusercontent.com/12747052/60470623-657d9300-9c61-11e9-967a-b5fff3df7921.png)

 Changing the material override setting to something else fixes the problem.

**Comment by thegrb93** [comment]
Closing in favor of #778
