### ISSUE TITLE
Wearing doesn't seem to actually do anything.

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#813]
Wearing doesn't seem to do anything in the editor. The console says the outfit's been applied but nothing changes, and players can't see it, whereas before they couldn't see it until you wore the outfit.

Tested on the most recent development branch with no addons, though it looks like it's kinda been like this for a while.

**Comment by iskawhiskers** [comment]
Can confirm.  Meta Construct's version of PAC3 has been doing this for upward of a year now, and after updating to the development branch, the problem persists even in singleplayer.  Other players have to manually request outfits whenever I wear an outfit; it's no longer automatically sent to other players >90% of the time, and it's the same issue for me trying to view other people's PAC outfits.

Workshop and master branches of PAC do not replicate this issue.  I thought it was compatibility issues with Outfitter at first, but testing with Python1320 looks to prove otherwise.

**Comment by thegrb93** [comment]
Any lua errors? The diff doesn't show anything that could break wearing. https://github.com/CapsAdmin/pac3/compare/master...develop

**Comment by iskawhiskers** [comment]
Negative https://i.imgur.com/4t8jbAM.png
Most of the errors for PAC3 I get in the console are just OGG/webaudio encoding errors, nothing that would relate to this.

**Comment by thegrb93** [comment]
You're sure the latest version of master doesn't replicate the issue?

**Comment by thegrb93** [comment]
The only other thing I can think of is a lua error is being caught but not displayed. I'll try reproducing the issue tonight.

**Comment by iskawhiskers** [comment]
> You're sure the latest version of master/workshop doesn't replicate the issue?

...what the hell?  Now that it's been brought up, even the workshop and master branches do it, too.  _No_ branch of PAC3 refreshes your own avatar on wear anymore.  I just tested it and now they do replicate the issue, despite not having done so for the past few months.  I really wish I knew the point where they stopped working.  It's like automatic outfit transmitting has been wiped from PAC3 entirely.

**Comment by thegrb93** [comment]
Well my server has had pac3 working forever so I'm inclined to believe it's an addon conflict, but I'll check tonight.

Can you describe the issue better btw? I'm still unsure what the actual issue is. You can't wear the outfit at all?

**Comment by iskawhiskers** [comment]
Mrwallace describes it as not being transmitted to other players even after being worn. 

For me, pressing the "Wear" button doesn't refresh my own outfit, and almost never transmits to other people -- they have to manually request outfits almost every single time.
I have the same issue the other way around trying to view other people's PAC outfits, where them wearing their own outfit won't wear it on _my_ end until I manually request outfits.

It seems like automatic outfit wearing is almost completely broken for me and a lot of other people on Meta in the same way.  I think it might be the same issue, but I don't know for sure, I'm just adding onto it since my issue is very similar.

**Comment by thegrb93** [comment]
Ok, sounds like a meta issue, but I'll check tonight.

**Comment by thegrb93** [comment]
Can't reproduce

**Comment by mrwallace888** [comment]
Weird. Before I could also TELL it was being worn because when you clicked "wear" the outfit would like sort of reset/respawn/disappear or something for a split second. But it hasn't done that so...

**Comment by mrwallace888** [comment]
And I don't think this is an addon conflict. Like I said, I had this issue with it being my only addon used.

**Comment by thegrb93** [comment]
So you're saying if I put a model part on myself, pac->wear, then nobody will be able to see that model?

**Comment by mrwallace888** [comment]
I suppose...? That's what happens for me, at least. And like I said, in older versions I was also able to tell when I wore something because of how it would like disappear for a nanosecond and come back, like as if it refreshed or reset or something. But it no longer does that so...

**Comment by thegrb93** [comment]
Maybe you have some kind of convar set? Try deleting cfg/client.vdf

**Comment by iskawhiskers** [comment]
Deleted client.vdf.  Outfit now refreshes for my client when worn when it's supposed to (tested in singleplayer).  It may be a convar being set by Meta, or a conflict with another addon that has to do with the player state like Outfitter.  I can't tell which convar(s) are causing it, but it seems to be a convar issue.

**Comment by thegrb93** [comment]
Glad that fixed it.
