### ISSUE TITLE
Other player's PAC outfits seem to be failing to load on player's client (Occasional. Somewhat inconsistent)

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#831]
While not completely sure as to why this happens, the use of the "Request Outfits" feature has almost become essential. Other player's PAC outfits don't seem to be automatically loading upon the player hitting the wear button, resulting in the only method of seeing their PACs to be requesting outfits. 

This doesn't seem like too much of an issue at first, but considering some players switch PACs frequently, and the fact that PAC3 used to be able to load PACs almost instantly to the client once worn serverside.. I'm beginning to believe this is at least a bug since I don't see exactly why it would be removed, unless there's any additional information that I'm missing.

**Comment by thegrb93** [comment]
Haven't seen this before. You could try clearing your cfg/client.vdf to reset convars to defaults, and I'll try verifying it soon.

**Comment by Techbot121** [comment]
yeah I've been testing this on the pac server today, it's most likely related to the wear filter. 
It works serverside (as in it get's the `wear` request) but it never gets send to the clients unless they request it themselves.

**Comment by Techbot121** [comment]
I looked at the filter and data.wear_filter sometimes has -2147483648 on the server, I think it's some overflow issue...

**Comment by roboderpy** [comment]
It is impossible for it to overflow unless there is code which is unaware of uid networking1:15, 7 октября 2019 г., Techbot121 <notifications@github.com>:I looked at the filter and data.wear_filter sometimes has -2147483648 on the server, I think it's some overflow issue...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/6d05e89bf2d5475fb13bc174e5b2b1beb7bfc992
