### ISSUE TITLE
PAC3 parts flickering in and out

### ISSUE THREAD

**Issue by liquiad** [CapsAdmin/pac3#833]
So I'm running a server on the Helix gamemode (it's basically just NutScript), and periodically PAC3 parts (specifically models) just start flickering in and out really fast. It's seemingly random and I've tried a lot of stuff to try and narrow down what's causing it, but haven't gotten anywhere.

Here's a video of what happens:
https://files.catbox.moe/ipq2lk.mp4

I honestly don't even know how to debug this kind of thing. I've gone down the rabbit hole of googling this issue and none of the fixes people suggested have made any difference. It's like this for everyone on the server, not just me.

Any ideas on how to narrow down the cause?

(i'm running on the latest develop branch, it did the same thing on the workshop version though)

**Comment by roboderpy** [comment]
seems like frame skipping issue, which is caused by other addons call render hooks in random order or call them between several frames. Please test with `pac_suppress_frames 0`. If issue would disappear, then it is "conflict" with third party addon (which im pretty sure it is). To fix this other addon should be consistent when and how it call draw functions.

**Comment by Techbot121** [comment]
the above command is now on by default (is now called `pac_optimization_render_once_per_frame`), if this still happens feel free to reopen.
