### ISSUE TITLE
IP Stealing Exploit

### ISSUE THREAD

**Issue by MayaMayaMayaMayaMayaMayaMayaMayaMaya** [CapsAdmin/pac3#912]
You can obtain other players' IP addresses (even as a client) by hosting custom sounds on your own webserver.

**Comment by thegrb93** [comment]
Yeah everyone knows this already. Disable custom content or disable pac3 if this irks you.

**Comment by thegrb93** [comment]
Other addons such as E2 streamcore or mediaplayer suffer as well.

**Comment by Techbot121** [comment]
I do not know how much you know about this topic since you made a throwaway account.

The practice of using images or similar for obtaining IP addresses is actually not that uncommon, many companies use a pixel sized Image in E-Mails to check if you have actually read them they're known as 'tracking pixels', that's also why most E-Mail clients block external image loading by default. 

### What **we** could do:
1. Create a centralized Server for content distribution
2. Add the ability to only load specific outfits (for example friends only)

**Number 1.** goes against the philosophy of PAC3 since we would have to handle the content of your outfits (privacy concerns etc...) and the implementation and running such a system is quite out of our scope.

**Number 2.** would allow only receiving the outfits you want to see. We already have a simple friends only option, but I guess it could be expanded to use the blacklist as well (not sure if it already does)

Since PAC3 uses the HTTP protocol there is not really much else we can do, at least to my knowledge.

### What **you** could do:
1. Limit receiving outfits to people you trust.
 You can enable friends only loading by enabling this setting
![settings](http://techbot.xyz/ShareX/screenshots/2020/06/01/gmod_14-23-29.png)
or by entering the console command `pac_friendonly 1` in your console

2. Use a VPN or similar to hide your real IP
3. Disable PAC3

I hope this helps.
