### ISSUE TITLE
Pac3 removed from workshop?

### ISSUE THREAD

**Issue by yourtoast4** [CapsAdmin/pac3#994]
Launched gmod earlier and realised pac3 wasn't up on the workshop and the addons tab says the addon was banned.

**Comment by CapsAdmin** [comment]
This has happened many times before. It's usually some AI who decides it's spam, bans it and is quickly unbanned by someone at facepunch.

I used to have someone at facepunch I could talk to directly to resolve this, but since that person doesn't work there anymore I'll have to submit an issue to facepunch. I don't know how long that will take.

In the meantime you can just download the project from github as that should work fine.

**Comment by dmamet** [comment]
How do I use the GitHub pac 3

**Comment by Yagira** [comment]
Download this https://github.com/CapsAdmin/pac3/archive/develop.zip
Extract to `Steam\steamapps\common\GarrysMod\garrysmod\addons`

**Comment by dmamet** [comment]
what do i extract from what and where

**Comment by kreevu** [comment]
> Download this https://github.com/CapsAdmin/pac3/archive/develop.zip
> Extract to `Steam\steamapps\common\GarrysMod\garrysmod\addons`

it still says its banned

**Comment by dmamet** [comment]
> > Download this https://github.com/CapsAdmin/pac3/archive/develop.zip
> > Extract to `Steam\steamapps\common\GarrysMod\garrysmod\addons`
> 
> it still says its banned

Its working for me

**Comment by CapsAdmin** [comment]
> > Download this https://github.com/CapsAdmin/pac3/archive/develop.zip
> > Extract to `Steam\steamapps\common\GarrysMod\garrysmod\addons`
> 
> it still says its banned

you probably need to unsubscribe or disable the workshop version

**Comment by CapsAdmin** [comment]
It's back again.

**Comment by Margen67** [comment]
#1175
